excel:
  file: web_cases.xlsx

logger:
  name: "python29"
  file: "python29log.txt"
  logger_level: "DEBUG"
  stream_level: "DEBUG"
  file_level: "INFO"

user:
  mobile_phone: "15512345678"
  pwd: "12345678"


selenium:
  wait_time: 20

