excel:
  file: "cases.xlsx"

default_logger:
  name: "test_default"
  logger_level: "DEBUG"
  stream_level: "DEBUG"
  file_level: "INFO"
  fmt: '[%(levelname)s  %(asctime)s  ] %(filename)s  line:%(lineno)d  msg:%(message)s'

db_mysql:
  host: "pftest.senguo.me"
  port: 3306
  user: "pftest"
  password: "senguo_mysql"
  charset: 'utf8'

db_redis:
  host: "pftest.senguo.me"
  port: "6379"
  auth: "senguo_redis"

db_mongo:
  host:
  port:


users:
  default_user:
    phone: "17386049001"
    password: "123456"

host:
  pf: "http://pftest.senguo.me"
  easy: "http://pftest.senguo.me/easy"
  center: "http://centertest.senguo.me"
